config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#welcome'
  # get '/authors/', to: 'authors#index', as: :authors
  # get '/authors/:id', to: 'authors#show', as: :author
  # get '/author/new', to: 'authors#new', as: :new_author
  resources :authors
  resources :posts
  resources :comments, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
#author.errors.full_message
class Author < ActiveRecord::Base
  validates :name, :surname, presence: true
  validates :age, numericality: { only_integer: true, greater_than: 18 }

  has_many :posts
  # has_many :author_posts
  # has_many :comments
  # has_many :post, through: :author_posts

  scope :old, -> { where('age > 30') }
  scope :young, -> { where('age < 20') }

  before_create :default_age

  def fullname
    "#{name} #{surname}"
  end

  private

  def default_age
    self.age = 25 unless age
  end

end

app/models/author_post.rb
class AuthorPost < ActiveRecord::Base
  belongs_to :author
  belongs_to :post
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :commentator_name, :content, presence: true

  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :content, presence: true
  validates :title, uniqueness: true
  validates :title, length: {maximum: 80}
  validates :content, length: {in: 10..500}

  belongs_to  :author, optional: true
  has_many :comments
  # has_many :author_posts
  # has_many :author, through: :author_posts

  scope :old, -> { where('created_at < ?', 40.minutes.ago) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.all
    @author = Author.new
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to author_params, notice: 'Author was created'
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      redirect_to authors_path, notice: 'Author was updated'
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
  end


  private

  def author_params
    params.require(:author).permit(:name, :surname, :age)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_url(comment_params[:post_id]), notice: 'Comment added'
    else
      redirect_to post_url(comment_params[:post_id]), alert: 'Something went wrong'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:commentator_name, :content, :post_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def welcome
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_params, notice: 'Post was created'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_params, notice: 'Post was updated'
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
     redirect_to posts_path, notice: 'Post was destroyed'
    else
     redirect_to posts_path, alert: 'There was an error while destroying. Please try again'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :author_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_author.html.erb
<div data-author-id="<%= author.id %>" class="row rowHeight">
  <div class="col-sm-8 col-md-2"><%= link_to author.fullname, author_path(id: author.id), class: 'postTitle'%>
  </div>
  <div class="col-sm-8 col-md-2"><%= link_to 'Edit', edit_author_path(id: author.id), role: 'button', class: 'btn btn-primary'%>
  </div>
  <div class="col-sm-8 col-md-2"><%= link_to 'Delete', author_path(id: author.id), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, role: 'button', class: 'btn btn-danger' %>
  </div>
</div>

app/views/authors/_form.erb
<% if @author.errors.any? %>
  <% @author.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger">
      <%= msg %>
    </div>
  <% end %>
<% end %>

<div class="container">
  <%= form_for @author, class: 'form-horizontal' do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'control-label col-sm-2'%>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :surname, class: 'control-label col-sm-2'%>
    <div class="col-sm-10">
      <%= f.text_field :surname, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :age, class: 'control-label col-sm-2'%>
    <div class="col-sm-10">
      <%= f.number_field :age, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Save', class: 'btn btn-default' %>
    </div>
  </div>
<% end %>
</div>

app/views/authors/create.js.erb
<% if @author.persisted? %>
  $('.table authors').append('<%= j render 'author', author: @author %>');
<% else %>
  alert('Ogarnij się'); alert('<%= j @author.errors.full_messages.join(', ') %>')
<% end %>

$('.new-author').find('input[type="text"], input[type="number"]').val('')

app/views/authors/destroy.js.erb
$('[data-author-id="<%= @author.id %>"]').remove()

app/views/authors/edit.html.erb
<h1>Edit author</h1>
<%= render 'form' %>

app/views/authors/index.html.erb
<h1>Authors</h1>
<img style="display: none;" src="https://i.redd.it/ounq1mw5kdxy.gif"/>

<table class="table authors">
  <% @authors.each do |author| %>
    <%= render 'author', author: author %>
  <% end %>
</table>
<hr/>

<div>
  <h1>New author</h1>
</div>
  <%= form_for @author, remote: true, format: :js, html: { class: 'new-author' } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'col-2'%>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :surname, class: 'control-label col-sm-2'%>
    <div class="col-sm-10">
      <%= f.text_field :surname, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :age, class: 'control-label col-sm-2'%>
    <div class="col-sm-10">
      <%= f.number_field :age, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Save', class: 'btn btn-default' %>
    </div>
  </div>
</div>
<% end %>

app/views/authors/new.html.erb
<h1>Add new author</h1>
<%= render 'form' %>

app/views/authors/show.html.erb
<h1>
  <%= @author.fullname %>
</h1>

<p>
  Age:
  <strong><%= @author.age %></strong>
  <hr/>

  Created_at
  <strong><%= @author.created_at %></strong>
  <hr/>

  Updated_at:
  <strong><%= @author.updated_at %></strong>
  <hr/>

  <h1>Author posts</h1>
  <% @author.posts.each do |post| %>
    <%= render 'posts/post', post: post %>
  <% end %>
</p>

app/views/comments/_comment.html.erb
<li class="list-group-item"><q><i><%= comment.content %></i></q> - <strong><%= comment.commentator_name %></strong></li>

app/views/comments/_form.erb
<br/>
<div class="container">
  <%= form_for @comment do |f| %>
  <div class="form-group">
    <%= f.label :commentator_name, class: 'control-label col-sm-3'%>
    <div class="col-sm-10">
      <%= f.email_field :commentator_name, required: true, placeholder: 'Enter email', class: 'form-control form-control-sm' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, class: 'control-label col-sm-3'%>
    <div class="col-sm-10">
      <%= f.text_area :content, required: true, minlength: 10, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Add comment', class: 'btn btn-default' %>
    </div>
  </div>
</div>

<%= f.hidden_field(:post_id, value: @post.id) %>

<% end %>

app/views/comments/_index.erb
<% if @post.comments %>
<div class="container"
    <ul class="list-group">
    <% @post.comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
    <% end %>
  </ul>
</div>

<% end %>

app/views/layouts/_flash.html.haml
-if alert
  .alert.alert-danger
    Alert: #{alert}

-if notice
  .alert.alert-success
    Success: #{notice}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous"/>
  </head>

  <body>
    <%= render 'layouts/partials/navbar' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/layouts/partials/_flash.erb
<% if alert  %>
<div class="alert alert-danger" role="alert">
 Alert:
 <%= alert %>
</div>
<% end %>

<% if notice %>
<div class="alert alert-success" role="alert">
 Success:
 <%= notice %>
</div>
<% end %>

app/views/layouts/partials/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path do %>
  <%= image_tag("blog.png", height: '120', width: '120') %>
<% end %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to root_path, class: "nav-link" do %>
      <span class="sr-only">(current)</span>
    <% end %>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Posts
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%= link_to 'New', new_post_path, class: 'dropdown-item' %>
      <%= link_to 'Index', posts_path, class: 'dropdown-item' %>
    </div>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Authors
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <% Author.all.each do |author| %>
        <%= link_to author.fullname, author_path(author.id), class: 'dropdown-item' %>
      <% end %>
      <div class="dropdown-divider"></div>
      <%= link_to 'New', new_author_path, class: 'dropdown-item' %>
      <%= link_to 'Index', authors_path, class: 'dropdown-item' %>
    </div>
  </li>

</ul>
</div>
</nav>

app/views/posts/_form.erb
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger">
      <%= msg %>
    </div>
  <% end %>
<% end %>

<div class="container">
  <%= form_for @post, class: 'form-horizontal' do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'control-label col-sm-2'%>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, class: 'control-label col-sm-2'%>
    <div class="col-sm-10">
      <%= f.text_area :content, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label Author, class: 'control-label col-sm-2'%>
    <div class="col-sm-10">
      <%= collection_select :post, :author_id, Author.all, :id, :fullname, {prompt: false}, class: 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Save', class: 'btn btn-default' %>
    </div>
  </div>
<% end %>
</div>

app/views/posts/_post.html.erb
<% if @author %>
  <% @author.posts.each do |post| %>
    <div class="row rowHeight">
      <div class="col-sm-12 col-md-6">
        <div class="postTitle"><%= link_to post.title, post_path(id: post.id) %>
        </div>
      </div>
      <div class="col-sm-12 col-md-2"><%= link_to 'Edit', edit_post_path(id: post.id), role: 'button', class: 'btn btn-primary'%>
      </div>
      <div class="col-sm-12 col-md-2"><%= link_to 'Delete', post_path(id: post.id), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, role: 'button', class: 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
<% else %>
  <% Post.all.each do |post| %>
    <div class="row rowHeight">
      <div class="col-sm-12 col-md-6">
        <div class="postTitle"><%= link_to post.title, post_path(id: post.id) %>
        </div>
      </div>
      <div class="col-sm-12 col-md-2"><%= link_to 'Edit', edit_post_path(id: post.id), role: 'button', class: 'btn btn-primary'%>
      </div>
      <div class="col-sm-12 col-md-2"><%= link_to 'Delete', post_path(id: post.id), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, role: 'button', class: 'btn btn-danger' %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Available posts</h1>
<div class="container">
    <%= render 'post' %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>
  <%= @post.title %>
</h1>

<p>
  Content:
  <strong><%= @post.content %></strong>
  <hr/>
  Author:
  <% if @post.author %>
    <strong><%= @post.author.fullname %></strong>
  <% end %>
  <hr/>
</p>
<h1>Comments</h1>
<ul>
<%= render 'comments/index' %>
<%= render 'comments/form' %>